<Project Sdk="Xamarin.Legacy.Sdk/0.2.0-alpha4">
  <PropertyGroup>
    <TargetFrameworks>net8.0-android34.0</TargetFrameworks>
    <SupportedOSPlatformVersion>33.0</SupportedOSPlatformVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Android.UsbSerial</AssemblyName>
    <RootNamespace>Hoho.Android.UsbSerial</RootNamespace>
  </PropertyGroup>
</Project>