<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android34.0</TargetFramework>
    <SupportedOSPlatformVersion>33.0</SupportedOSPlatformVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Android.UsbSerial</AssemblyName>
    <RootNamespace>Hoho.Android.UsbSerial</RootNamespace>
  </PropertyGroup>
</Project>