<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android36.1</TargetFramework>
    <SupportedOSPlatformVersion>33.0</SupportedOSPlatformVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Android.UsbSerial</AssemblyName>
    <RootNamespace>Hoho.Android.UsbSerial</RootNamespace>
  </PropertyGroup>
</Project>